# Generated by Django 4.2.23 on 2025-08-16 16:10

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketplace", "0012_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTracker",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stripe_payment_intent_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("stripe_refund_id", models.CharField(blank=True, db_index=True, max_length=255)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("payment", "Payment"), ("refund", "Refund"), ("partial_refund", "Partial Refund")],
                        default="payment",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_trackers",
                        to="marketplace.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_trackers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_trackers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stripe_payment_intent_id", models.CharField(db_index=True, max_length=255)),
                ("stripe_checkout_session_id", models.CharField(db_index=True, max_length=255)),
                (
                    "transfer_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Stripe transfer ID when payment is transferred to seller",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("held", "On Hold"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("released", "Released to Seller"),
                            ("disputed", "Disputed"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("platform_fee", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("stripe_fee", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount to be paid to seller after fees", max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("item_count", models.PositiveIntegerField(default=1)),
                ("item_names", models.TextField(help_text="Comma-separated list of item names")),
                (
                    "hold_reason",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Hold Period"),
                            ("new_seller", "New Seller Verification"),
                            ("high_value", "High Value Transaction"),
                            ("suspicious", "Suspicious Activity"),
                            ("dispute", "Dispute Filed"),
                            ("manual", "Manual Hold"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                (
                    "days_to_hold",
                    models.PositiveIntegerField(default=30, help_text="Number of days to hold payment (default: 30)"),
                ),
                ("hold_start_date", models.DateTimeField(blank=True, help_text="When hold period started", null=True)),
                (
                    "planned_release_date",
                    models.DateTimeField(blank=True, help_text="Calculated release date", null=True),
                ),
                (
                    "actual_release_date",
                    models.DateTimeField(blank=True, help_text="When payment was actually released", null=True),
                ),
                ("hold_notes", models.TextField(blank=True)),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                ("payment_received_date", models.DateTimeField(blank=True, null=True)),
                (
                    "payed_out",
                    models.BooleanField(
                        default=False, help_text="True if this transfer has been included in a payout"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="marketplace.order",
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "stripe_payout_id",
                    models.CharField(db_index=True, help_text="Stripe payout ID", max_length=255, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_transit", "In Transit"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payout_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Payout"),
                            ("express", "Express Payout"),
                            ("instant", "Instant Payout"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("amount_cents", models.PositiveIntegerField(help_text="Total payout amount in cents")),
                (
                    "amount_decimal",
                    models.DecimalField(
                        decimal_places=2, help_text="Total payout amount in decimal format", max_digits=10
                    ),
                ),
                ("currency", models.CharField(help_text="Payout currency", max_length=3)),
                (
                    "source_type",
                    models.CharField(default="bank_account", help_text="Source type for payout", max_length=20),
                ),
                (
                    "bank_account_last4",
                    models.CharField(blank=True, help_text="Last 4 digits of bank account", max_length=4),
                ),
                ("bank_name", models.CharField(blank=True, help_text="Bank name", max_length=100)),
                (
                    "transfer_count",
                    models.PositiveIntegerField(default=0, help_text="Number of payment transfers included"),
                ),
                (
                    "total_gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total gross amount from all transfers",
                        max_digits=12,
                    ),
                ),
                (
                    "total_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), help_text="Total fees deducted", max_digits=10
                    ),
                ),
                (
                    "stripe_created_at",
                    models.DateTimeField(blank=True, help_text="When payout was created in Stripe", null=True),
                ),
                ("arrival_date", models.DateTimeField(blank=True, help_text="Expected arrival date", null=True)),
                (
                    "failure_code",
                    models.CharField(blank=True, help_text="Stripe failure code if failed", max_length=50),
                ),
                ("failure_message", models.TextField(blank=True, help_text="Failure message from Stripe")),
                ("description", models.TextField(blank=True, help_text="Description of the payout")),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Additional metadata")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="Seller receiving the payout",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_payouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stripe_event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("processing_attempts", models.IntegerField(default=0)),
                ("last_processing_error", models.TextField(blank=True)),
                ("event_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment_tracker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="payment_system.paymenttracker",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_currency", models.CharField(help_text="Base currency code (e.g., USD, EUR)", max_length=3)),
                ("target_currency", models.CharField(help_text="Target currency code (e.g., EUR, GBP)", max_length=3)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6, help_text="Exchange rate from base to target currency", max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="When this rate was recorded")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When this rate was last updated")),
                (
                    "source",
                    models.CharField(default="manual", help_text="Source of this exchange rate data", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this rate is currently active")),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "db_table": "payment_exchange_rates",
                "ordering": ["-created_at", "base_currency", "target_currency"],
                "indexes": [
                    models.Index(
                        fields=["base_currency", "target_currency", "-created_at"],
                        name="payment_exc_base_cu_a24be2_idx",
                    ),
                    models.Index(fields=["created_at"], name="payment_exc_created_d77919_idx"),
                    models.Index(fields=["is_active"], name="payment_exc_is_acti_3c76c1_idx"),
                ],
                "unique_together": {("base_currency", "target_currency", "created_at")},
            },
        ),
        migrations.CreateModel(
            name="PayoutItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "transfer_amount",
                    models.DecimalField(decimal_places=2, help_text="Net amount of this transfer", max_digits=10),
                ),
                ("transfer_currency", models.CharField(help_text="Currency of the transfer", max_length=3)),
                ("transfer_date", models.DateTimeField(help_text="When the transfer was completed")),
                ("order_id", models.CharField(help_text="Order ID for reference", max_length=100)),
                ("item_names", models.TextField(help_text="Items sold in this transfer")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_transfer",
                    models.ForeignKey(
                        help_text="The payment transfer included in the payout",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_items",
                        to="payment_system.paymenttransaction",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        help_text="The payout this item belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_items",
                        to="payment_system.payout",
                    ),
                ),
            ],
            options={
                "db_table": "payment_payout_items",
                "ordering": ["-transfer_date"],
                "indexes": [
                    models.Index(fields=["payout", "-transfer_date"], name="payment_pay_payout__ac0ced_idx"),
                    models.Index(fields=["payment_transfer"], name="payment_pay_payment_9946f7_idx"),
                    models.Index(fields=["order_id"], name="payment_pay_order_i_4b775b_idx"),
                ],
                "unique_together": {("payment_transfer",)},
            },
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(fields=["seller", "-created_at"], name="payment_pay_seller__ae2673_idx"),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(fields=["status", "-created_at"], name="payment_pay_status_2c81ae_idx"),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(fields=["stripe_payout_id"], name="payment_pay_stripe__d88a8b_idx"),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(fields=["currency", "-created_at"], name="payment_pay_currenc_ab034c_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["seller", "status"], name="payment_tra_seller__4dcbf8_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["buyer", "purchase_date"], name="payment_tra_buyer_i_bfee87_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["stripe_payment_intent_id"], name="payment_tra_stripe__83a4b4_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["stripe_checkout_session_id"], name="payment_tra_stripe__4865ca_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["status", "planned_release_date"], name="payment_tra_status_22f2ca_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(fields=["hold_start_date"], name="payment_tra_hold_st_f71ab5_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttracker",
            index=models.Index(fields=["stripe_payment_intent_id"], name="payment_tra_stripe__0c56e8_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttracker",
            index=models.Index(fields=["stripe_refund_id"], name="payment_tra_stripe__93371c_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttracker",
            index=models.Index(fields=["order", "transaction_type"], name="payment_tra_order_i_21f0ad_idx"),
        ),
        migrations.AddIndex(
            model_name="paymenttracker",
            index=models.Index(fields=["user", "status"], name="payment_tra_user_id_badafc_idx"),
        ),
    ]
