# Generated by Django 5.2.4 on 2025-08-13 22:01

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_product_price'),
        ('payment_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=255)),
                ('stripe_checkout_session_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('held', 'On Hold'), ('processing', 'Processing'), ('released', 'Released to Seller'), ('disputed', 'Disputed'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('stripe_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid to seller after fees', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('item_count', models.PositiveIntegerField(default=1)),
                ('item_names', models.TextField(help_text='Comma-separated list of item names')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('payment_received_date', models.DateTimeField(blank=True, null=True)),
                ('hold_release_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='marketplace.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.CharField(max_length=200)),
                ('product_sku', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='marketplace.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='marketplace.product')),
                ('payment_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='payment_system.paymenttransaction')),
            ],
            options={
                'db_table': 'payment_items',
                'ordering': ['payment_transaction', 'product_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('standard', 'Standard Hold Period'), ('new_seller', 'New Seller Verification'), ('high_value', 'High Value Transaction'), ('suspicious', 'Suspicious Activity'), ('dispute', 'Dispute Filed'), ('manual', 'Manual Hold')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active Hold'), ('released', 'Released'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('hold_days', models.PositiveIntegerField(default=7, help_text='Number of days to hold payment')),
                ('hold_start_date', models.DateTimeField(auto_now_add=True)),
                ('planned_release_date', models.DateTimeField()),
                ('actual_release_date', models.DateTimeField(blank=True, null=True)),
                ('hold_notes', models.TextField(blank=True)),
                ('release_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_holds_created', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_holds_released', to=settings.AUTH_USER_MODEL)),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_hold', to='payment_system.paymenttransaction')),
            ],
            options={
                'db_table': 'payment_holds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['seller', 'status'], name='payment_tra_seller__4dcbf8_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['buyer', 'purchase_date'], name='payment_tra_buyer_i_bfee87_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payment_tra_stripe__83a4b4_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['stripe_checkout_session_id'], name='payment_tra_stripe__4865ca_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'hold_release_date'], name='payment_tra_status_429d35_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentitem',
            index=models.Index(fields=['payment_transaction', 'product'], name='payment_ite_payment_085634_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthold',
            index=models.Index(fields=['status', 'planned_release_date'], name='payment_hol_status_03a0de_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthold',
            index=models.Index(fields=['payment_transaction', 'status'], name='payment_hol_payment_afa58d_idx'),
        ),
    ]
