# Generated by Django 4.2.23 on 2025-08-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payoutitem',
            unique_together=set(),
        ),
    ]
