# Generated by Django 5.2.4 on 2025-08-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0002_paymenttransaction_paymentitem_paymenthold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthold',
            name='hold_days',
            field=models.PositiveIntegerField(default=7, help_text='Fixed 7-day hold period for all purchases'),
        ),
        migrations.AlterField(
            model_name='paymenthold',
            name='planned_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
