# Generated by Django 4.2.23 on 2025-08-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_system", "0003_add_payment_intent_failure_tracking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="payment_failure_code",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="payment_failure_reason",
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("held", "On Hold"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("released", "Released to Seller"),
                    ("disputed", "Disputed"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="WebhookEvent",
        ),
    ]
