# Generated by Django 4.2.23 on 2025-08-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0005_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttracker',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttracker',
            name='transaction_type',
            field=models.CharField(choices=[('payment', 'Payment'), ('refund', 'Refund'), ('partial_refund', 'Partial Refund'), ('payment_intent', 'Payment Intent'), ('transfer', 'Transfer')], default='payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('held', 'On Hold'), ('processing', 'Processing'), ('completed', 'Completed'), ('released', 'Released to Seller'), ('disputed', 'Disputed'), ('waiting_refund', 'Waiting for Refund'), ('refunded', 'Refunded'), ('failed_refund', 'Failed Refund'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
