# Generated by Django 4.2.23 on 2025-08-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_system", "0006_paymenttracker_stripe_transfer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="last_retry_at",
            field=models.DateTimeField(blank=True, help_text="Timestamp of last retry attempt", null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="performance_metrics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Performance metrics: API response times, database query times, etc.",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="processing_completed_at",
            field=models.DateTimeField(blank=True, help_text="When payout processing completed", null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="processing_duration_ms",
            field=models.PositiveIntegerField(blank=True, help_text="Processing duration in milliseconds", null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, help_text="When payout processing began", null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="reconciled_at",
            field=models.DateTimeField(blank=True, help_text="When reconciliation was completed", null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="reconciliation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Reconciliation"),
                    ("matched", "Successfully Matched"),
                    ("mismatched", "Mismatched"),
                    ("manual_review", "Requires Manual Review"),
                ],
                default="pending",
                help_text="Reconciliation status against bank records",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="retry_count",
            field=models.PositiveIntegerField(default=0, help_text="Number of retry attempts for failed payouts"),
        ),
        migrations.AddField(
            model_name="payout",
            name="status_history",
            field=models.JSONField(
                blank=True, default=list, help_text="Audit trail of status changes with timestamps and reasons"
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(fields=["reconciliation_status", "-created_at"], name="payment_pay_reconci_237788_idx"),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(fields=["processing_started_at"], name="payment_pay_process_f0520b_idx"),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(fields=["retry_count", "-last_retry_at"], name="payment_pay_retry_c_7c7c8e_idx"),
        ),
    ]
