# Generated by Django 4.2.23 on 2025-08-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0006_add_exchange_rate_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payment_tra_status_429d35_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='payment_exc_base_cu_a24be2_idx',
            old_name='payment_exc_base_cu_ab5a15_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='payment_exc_created_d77919_idx',
            old_name='payment_exc_created_b9b6c4_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='payment_exc_is_acti_3c76c1_idx',
            old_name='payment_exc_is_acti_e92d3e_idx',
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'planned_release_date'], name='payment_tra_status_22f2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['hold_start_date'], name='payment_tra_hold_st_f71ab5_idx'),
        ),
    ]
