# Generated by Django 4.2.23 on 2025-08-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0007_add_transfer_state_management'),
        ('payment_system', '0007_remove_paymenttransaction_payment_tra_status_429d35_idx_and_more'),
    ]

    operations = [
    ]
