# Generated by Django 4.2.23 on 2025-08-21 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0007_add_payout_status_choices'),
        ('payment_system', '0008_remove_payout_payment_pay_reconci_237788_idx_and_more'),
    ]

    operations = [
    ]
