# Generated by Django 5.2.4 on 2025-08-15 15:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_system', '0008_merge_20250814_2347'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payout_id', models.CharField(db_index=True, help_text='Stripe payout ID', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('payout_type', models.CharField(choices=[('standard', 'Standard Payout'), ('express', 'Express Payout'), ('instant', 'Instant Payout')], default='standard', max_length=20)),
                ('amount_cents', models.PositiveIntegerField(help_text='Total payout amount in cents')),
                ('amount_decimal', models.DecimalField(decimal_places=2, help_text='Total payout amount in decimal format', max_digits=10)),
                ('currency', models.CharField(help_text='Payout currency', max_length=3)),
                ('source_type', models.CharField(default='bank_account', help_text='Source type for payout', max_length=20)),
                ('bank_account_last4', models.CharField(blank=True, help_text='Last 4 digits of bank account', max_length=4)),
                ('bank_name', models.CharField(blank=True, help_text='Bank name', max_length=100)),
                ('transfer_count', models.PositiveIntegerField(default=0, help_text='Number of payment transfers included')),
                ('total_gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total gross amount from all transfers', max_digits=12)),
                ('total_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total fees deducted', max_digits=10)),
                ('stripe_created_at', models.DateTimeField(blank=True, help_text='When payout was created in Stripe', null=True)),
                ('arrival_date', models.DateTimeField(blank=True, help_text='Expected arrival date', null=True)),
                ('failure_code', models.CharField(blank=True, help_text='Stripe failure code if failed', max_length=50)),
                ('failure_message', models.TextField(blank=True, help_text='Failure message from Stripe')),
                ('description', models.TextField(blank=True, help_text='Description of the payout')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_amount', models.DecimalField(decimal_places=2, help_text='Net amount of this transfer', max_digits=10)),
                ('transfer_currency', models.CharField(help_text='Currency of the transfer', max_length=3)),
                ('transfer_date', models.DateTimeField(help_text='When the transfer was completed')),
                ('order_id', models.CharField(help_text='Order ID for reference', max_length=100)),
                ('item_names', models.TextField(help_text='Items sold in this transfer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_payout_items',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payment_tra_transfe_3f4d8f_idx',
        ),
        migrations.AddField(
            model_name='payout',
            name='seller',
            field=models.ForeignKey(help_text='Seller receiving the payout', on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payoutitem',
            name='payment_transfer',
            field=models.ForeignKey(help_text='The payment transfer included in the payout', on_delete=django.db.models.deletion.CASCADE, related_name='payout_items', to='payment_system.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='payoutitem',
            name='payout',
            field=models.ForeignKey(help_text='The payout this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payout_items', to='payment_system.payout'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['seller', '-created_at'], name='payment_pay_seller__ae2673_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', '-created_at'], name='payment_pay_status_2c81ae_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['stripe_payout_id'], name='payment_pay_stripe__d88a8b_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['currency', '-created_at'], name='payment_pay_currenc_ab034c_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['payout', '-transfer_date'], name='payment_pay_payout__ac0ced_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['payment_transfer'], name='payment_pay_payment_9946f7_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutitem',
            index=models.Index(fields=['order_id'], name='payment_pay_order_i_4b775b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payoutitem',
            unique_together={('payment_transfer',)},
        ),
    ]
