# Generated by Django 5.2.5 on 2025-11-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    models.CharField(
                        choices=[("android", "Android"), ("ios", "iOS")],
                        help_text="Platform (Android or iOS)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "mandatory_version",
                    models.CharField(help_text="Minimum required version (e.g., '1.3.0')", max_length=20),
                ),
                (
                    "latest_version",
                    models.CharField(help_text="Latest available version (e.g., '1.4.0')", max_length=20),
                ),
                (
                    "update_message",
                    models.TextField(blank=True, help_text="Message to show users when update is required"),
                ),
                ("download_url", models.URLField(blank=True, help_text="URL to download the latest version")),
                ("is_active", models.BooleanField(default=True, help_text="Whether this version check is active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "App Version",
                "verbose_name_plural": "App Versions",
                "ordering": ["platform"],
            },
        ),
    ]
