# Generated by Django 5.2.5 on 2025-11-14 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductARModelDownload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("local_path", models.CharField(max_length=1024)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("platform", models.CharField(blank=True, max_length=64)),
                ("app_version", models.CharField(blank=True, max_length=64)),
                ("device_info", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="downloads", to="ar.productarmodel"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ar_model_downloads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product 3D Model Download",
                "verbose_name_plural": "Product 3D Model Downloads",
                "ordering": ["-created_at"],
            },
        ),
    ]
