# Generated by Django 5.2.5 on 2025-11-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ar", "0002_productarmodeldownload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productarmodeldownload",
            name="file_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="productarmodeldownload",
            name="local_path",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
