# Generated by Django 5.2.4 on 2025-08-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_order_is_locked_order_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
