# Generated by Django 5.2.4 on 2025-08-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0009_alter_cart_options_remove_cart_locked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Pending Payment"),
                    ("payment_confirmed", "Payment Confirmed"),
                    ("processing", "Processing"),
                    ("awaiting_shipment", "Awaiting Shipment"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
