# Generated by Django 4.2.23 on 2025-08-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_optimize_product_queries"),
        ("marketplace", "0012_alter_product_price"),
    ]

    operations = []
