# Generated by Django 4.2.23 on 2025-08-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0013_merge_20250816_2310"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="productfavorite",
            name="marketplace_productfavorite_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="productimage",
            name="marketplace_productimage_product_primary_idx",
        ),
        migrations.RemoveIndex(
            model_name="productreview",
            name="marketplace_productreview_product_active_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="marketplace_is_acti_39fb3f_idx",
            old_name="marketplace_product_active_created_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="marketplace_is_acti_098562_idx",
            old_name="marketplace_product_active_price_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="marketplace_is_acti_9074ca_idx",
            old_name="marketplace_product_active_views_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="marketplace_is_acti_e6a6e3_idx",
            old_name="marketplace_product_active_favorites_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="marketplace_categor_50d755_idx",
            old_name="marketplace_product_category_active_created_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="marketplace_seller__04db12_idx",
            old_name="marketplace_product_seller_active_created_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="marketplace_brand_3733ba_idx",
            old_name="marketplace_product_brand_active_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="marketplace_conditi_407382_idx",
            old_name="marketplace_product_condition_active_idx",
        ),
        migrations.RenameIndex(
            model_name="product",
            new_name="marketplace_stock_q_f563e5_idx",
            old_name="marketplace_product_stock_active_idx",
        ),
        migrations.RenameIndex(
            model_name="productfavorite",
            new_name="marketplace_user_id_2d7f2b_idx",
            old_name="marketplace_productfavorite_user_product_idx",
        ),
        migrations.RenameIndex(
            model_name="productfavorite",
            new_name="marketplace_product_1a9f1e_idx",
            old_name="marketplace_productfavorite_product_idx",
        ),
        migrations.RenameIndex(
            model_name="productfavorite",
            new_name="marketplace_user_id_6e8094_idx",
            old_name="marketplace_productfavorite_user_idx",
        ),
        migrations.AddIndex(
            model_name="productfavorite",
            index=models.Index(fields=["created_at"], name="marketplace_created_8405ab_idx"),
        ),
    ]
