# Generated by Django 4.2.23 on 2025-08-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_add_s3_fields_to_productimage'),
        ('marketplace', '0015_alter_order_payment_status'),
    ]

    operations = [
    ]
