# Generated by Django 5.2.4 on 2025-08-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0016_merge_20250821_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_image",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
