# Generated by Django 5.2.4 on 2025-12-24 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0018_productreview_helpful_count_productreviewhelpful'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_confirmed', 'Payment Confirmed'), ('awaiting_shipment', 'Awaiting Shipment'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('return_requested', 'Return Requested'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending_payment', max_length=20),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('defective', 'Defective Product'), ('wrong_item', 'Wrong Item Shipped'), ('size_too_small', 'Size Too Small'), ('size_too_large', 'Size Too Large'), ('change_of_mind', 'Change of Mind'), ('other', 'Other')], default='other', max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('proof_image_urls', models.JSONField(blank=True, help_text='List of URLs for proof images', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='marketplace.order')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return Request',
                'verbose_name_plural': 'Return Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
