# Generated by Django 5.2.4 on 2025-12-26
# GDPR compliance: Allow ProductReview.reviewer to be NULL for user deletion

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0019_product_average_rating_product_review_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Add reviewer_name field to store display name when reviewer is anonymized
        migrations.AddField(
            model_name="productreview",
            name="reviewer_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        # Remove old unique_together constraint
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together=set(),
        ),
        # Modify reviewer field to allow null and use SET_NULL
        migrations.AlterField(
            model_name="productreview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Add new constraint that only applies when reviewer is not null
        migrations.AddConstraint(
            model_name="productreview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reviewer__isnull", False)),
                fields=("product", "reviewer"),
                name="unique_product_reviewer",
            ),
        ),
    ]
