# Kong Declarative Configuration (DB-less mode alternative)
# This file can be used for Kong DB-less mode or as reference for API configuration

_format_version: "3.0"

# Services - Backend services Kong will proxy to
services:
  # Authentication Service
  - name: authentication-service
    url: http://host.docker.internal:8000
    protocol: http
    host: host.docker.internal
    port: 8000
    path: /
    retries: 5
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000

    # Routes for authentication service
    routes:
      # Public Routes (No JWT required)
      - name: auth-login
        paths:
          - /api/auth/login
        methods:
          - POST
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 5
              policy: local
              fault_tolerant: true
          - name: prometheus
            config:
              status_code_metrics: true
              latency_metrics: true

      - name: auth-register
        paths:
          - /api/auth/register
        methods:
          - POST
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 3
              policy: local
          - name: prometheus

      - name: auth-verify-email
        paths:
          - /api/auth/verify-email
        methods:
          - POST
          - GET
        strip_path: false

      - name: auth-google-oauth
        paths:
          - /api/auth/google
        methods:
          - POST
        strip_path: false

      - name: auth-refresh-token
        paths:
          - /api/auth/token/refresh
        methods:
          - POST
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 10
              policy: local

      # Protected Routes (JWT required)
      - name: auth-profile
        paths:
          - /api/auth/profile
        methods:
          - GET
          - PUT
          - PATCH
        strip_path: false
        plugins:
          - name: jwt
            config:
              key_claim_name: sub
              secret_is_base64: false
              claims_to_verify:
                - exp
          - name: rate-limiting
            config:
              minute: 60
              policy: local
          - name: prometheus

      - name: auth-2fa
        paths:
          - /api/auth/2fa
        methods:
          - POST
          - GET
        strip_path: false
        plugins:
          - name: jwt
          - name: rate-limiting
            config:
              minute: 10
              policy: local

      - name: seller-apply
        paths:
          - /api/auth/seller/apply
        methods:
          - POST
        strip_path: false
        plugins:
          - name: jwt
          - name: rate-limiting
            config:
              hour: 2
              policy: local
          - name: prometheus

      - name: seller-status
        paths:
          - /api/auth/seller/status
        methods:
          - GET
        strip_path: false
        plugins:
          - name: jwt
          - name: rate-limiting
            config:
              minute: 20
              policy: local
  # Marketplace Service (Phase 3)
  - name: marketplace-service
    url: http://host.docker.internal:8000
    protocol: http
    host: host.docker.internal
    port: 8000
    path: /
    retries: 5
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    routes:
      # Public Routes
      - name: marketplace-products
        paths:
          - /api/marketplace/products
          - /api/marketplace/products/*
        methods:
          - GET
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 100
              policy: local
          - name: prometheus
      - name: marketplace-categories
        paths:
          - /api/marketplace/categories
          - /api/marketplace/categories/*
        methods:
          - GET
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 100
              policy: local
          - name: prometheus
      - name: marketplace-search
        paths:
          - /api/marketplace/products/search
          - /api/marketplace/products/autocomplete
          - /api/marketplace/products/filters
        methods:
          - GET
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 100
              policy: local
          - name: prometheus
      # Protected Routes (JWT required)
      - name: marketplace-cart
        paths:
          - /api/marketplace/cart
          - /api/marketplace/cart/*
        methods:
          - GET
          - POST
          - PUT
          - DELETE
          - PATCH
        strip_path: false
        plugins:
          - name: jwt
          - name: rate-limiting
            config:
              minute: 60
              policy: local
          - name: prometheus
      - name: marketplace-orders
        paths:
          - /api/marketplace/orders
          - /api/marketplace/orders/*
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
        strip_path: false
        plugins:
          - name: jwt
          - name: rate-limiting
            config:
              minute: 60
              policy: local
          - name: prometheus
      - name: marketplace-reviews
        paths:
          - /api/marketplace/reviews
          - /api/marketplace/reviews/*
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
        strip_path: false
        plugins:
          - name: jwt
          - name: rate-limiting
            config:
              minute: 60
              policy: local
          - name: prometheus
      - name: marketplace-metrics
        paths:
          - /api/marketplace/metrics
          - /api/marketplace/metrics/*
        methods:
          - GET
        strip_path: false
        plugins:
          - name: jwt
          - name: rate-limiting
            config:
              minute: 60
              policy: local
          - name: prometheus
      - name: marketplace-profiles
        paths:
          - /api/marketplace/profiles
          - /api/marketplace/profiles/*
        methods:
          - GET
          - POST
          - PUT
          - PATCH
        strip_path: false
        plugins:
          - name: jwt
          - name: rate-limiting
            config:
              minute: 60
              policy: local
          - name: prometheus
      - name: marketplace-seller-profile
        paths:
          - /api/marketplace/sellers/*
        methods:
          - GET
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 100
              policy: local
          - name: prometheus
      # Internal APIs (NOT exposed publicly, but defined for completeness)
      # These paths should be blocked at a lower level (e.g., Nginx, firewall)
      # Or protected by a separate internal Kong service if internal APIs are routed differently
      - name: marketplace-internal-product
        paths:
          - /api/marketplace/internal/products/*
        methods:
          - GET
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 1000
              policy: local
          - name: prometheus
      - name: marketplace-internal-order
        paths:
          - /api/marketplace/internal/orders/*
        methods:
          - GET
        strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 1000
              policy: local
          - name: prometheus

# Global Plugins (applied to all routes)
plugins:
  - name: correlation-id
    config:
      header_name: X-Correlation-ID
      generator: uuid
      echo_downstream: true

  - name: request-id
    config:
      header_name: X-Request-ID
      generator: uuid
      echo_downstream: true

  # Prometheus metrics collection
  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true
      upstream_health_metrics: true

# Consumers (JWT credentials for testing)
consumers:
  - username: test-user
    custom_id: test-user-001
    jwt_secrets:
      - key: designia-jwt-key
        algorithm: HS256
        secret: your-secret-key-here
