"""
Django settings for designiaBackend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import os
from datetime import timedelta
from pathlib import Path

import pymysql
from dotenv import load_dotenv

# Install PyMySQL as MySQLdb (compatibility with Django's MySQL backend)
pymysql.install_as_MySQLdb()

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: don't run with debug turned on in production!
# SECURITY FIX: Default to False to prevent information disclosure in production
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY FIX: Require SECRET_KEY environment variable in production
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable must be set in production")

# Parse ALLOWED_HOSTS from environment variable
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "192.168.3.2,localhost,127.0.0.1").split(",")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",  # WebSocket support
    "rest_framework",
    "corsheaders",
    "django_filters",
    "storages",  # AWS S3 storage backend
    "django_celery_beat",  # Celery Beat for scheduled tasks
    "drf_spectacular",  # OpenAPI/Swagger documentation
    "infrastructure",  # Infrastructure abstractions (SOLID refactoring)
    "authentication",
    "marketplace",
    "activity",
    "payment_system",
    "chat",
    "system_info",
    "ar",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",  # Enable CSRF protection; JWT auth endpoints are exempt by default
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Security headers for Google OAuth
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

ROOT_URLCONF = "designiaBackend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "designiaBackend.wsgi.application"
ASGI_APPLICATION = "designiaBackend.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database Configuration - default to SQLite for local dev, allow MySQL via env


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME", "designia_db"),
        "USER": os.getenv("DB_USER", "admin"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            "charset": "utf8mb4",
            "use_unicode": True,
        },
        "CONN_MAX_AGE": 60,
        "CONN_HEALTH_CHECKS": True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = "authentication.CustomUser"

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "60/min", "user": "120/min"},
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

# drf-spectacular settings for OpenAPI/Swagger documentation
SPECTACULAR_SETTINGS = {
    "TITLE": "Designia Backend API",
    "DESCRIPTION": "API documentation for Designia marketplace platform",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    "APPEND_COMPONENTS": {
        "securitySchemes": {
            "Bearer": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "SECURITY": [{"Bearer": []}],
}


# JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "TOKEN_OBTAIN_SERIALIZER": "authentication.jwt_serializers.CustomTokenObtainPairSerializer",
}

# CORS settings - parse from environment variable
_cors_origins_default = "http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173,http://127.0.0.1:5174,http://localhost:8080,http://127.0.0.1:8080,http://localhost:8081,http://127.0.0.1:8081"
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", _cors_origins_default).split(",")

CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings for Google OAuth
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://accounts\.google\.com$",
    r"^https://.*\.google\.com$",
    r"^https://.*\.gstatic\.com$",
]


# Security headers for Google OAuth
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Disable CSRF for API endpoints since we're using JWT authentication
CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173,http://127.0.0.1:5174",
).split(",")

# AWS S3 / MinIO Storage Configuration
USE_S3 = os.getenv("USE_S3", "False").lower() == "true"


def _env_str(name: str, default: str = "") -> str:
    value = os.getenv(name, default)
    return value.strip() if isinstance(value, str) else value


BASE_URL = _env_str("BASE_URL", "")
S3_USE_PROXY_FOR_PUBLIC_URLS = os.getenv("S3_USE_PROXY_FOR_PUBLIC_URLS", "True").lower() == "true"
S3_USE_PROXY_FOR_IMAGE_LINKS = os.getenv("S3_USE_PROXY_FOR_IMAGE_LINKS", "True").lower() == "true"
S3_USE_PROXY_FOR_MODEL_LINKS = os.getenv("S3_USE_PROXY_FOR_MODEL_LINKS", "True").lower() == "true"
S3_PROXY_BASE_PATH = _env_str("S3_PROXY_BASE_PATH", "/api/system/s3-images")
S3_PROXY_BASE_URL = _env_str("S3_PROXY_BASE_URL", BASE_URL)

# S3 is always mandatory
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")
AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")

_env_verify = os.getenv("AWS_S3_VERIFY")
AWS_S3_VERIFY = (_env_verify.lower() == "true") if _env_verify is not None else True

AWS_DEFAULT_ACL = None
AWS_S3_ADDRESSING_STYLE = "path"
AWS_S3_SIGNATURE_VERSION = "s3v4"

# Use S3 for media only
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# Static files from local /static/ path
BASE_DIR = Path(__file__).resolve().parent.parent
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

print(f"BASE_DIR: {BASE_DIR}")
print(f"STATIC_ROOT: {STATIC_ROOT}")
print(f"STATIC_URL: {STATIC_URL}")

# Media files go to S3
base = (AWS_S3_ENDPOINT_URL or "").rstrip("/")
if base:
    MEDIA_URL = f"{base}/{AWS_STORAGE_BUCKET_NAME}/media/"
else:
    MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/media/"

# Email settings
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@todoist.com")

# For development: set EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend in .env
# For production: set EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend in .env

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "debug.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "marketplace": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "marketplace.serializers": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "authentication": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "authentication.views": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "authentication.serializers": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "authentication.models": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "activity": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "activity.models": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "activity.views": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "payment_system": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

# ===============================
# STRIPE PAYMENT SYSTEM SETTINGS
# ===============================

# Stripe configuration
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
STRIPE_WEBHOOK_CONNECT_SECRET = os.getenv("STRIPE_WEBHOOK_CONNECT_SECRET", "")

# Marketplace commission (percentage)
STRIPE_APPLICATION_FEE_PERCENT = float(os.getenv("STRIPE_APPLICATION_FEE_PERCENT", "5.0"))

# Frontend URL for redirects
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")

# Ensure FRONTEND_URL is present in CORS/CSRF lists
if FRONTEND_URL and FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)
if FRONTEND_URL and FRONTEND_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)

# Payment security settings
PAYMENT_WHITELISTED_IPS = os.getenv("PAYMENT_WHITELISTED_IPS", "127.0.0.1,localhost").split(",")

# Cache configuration for rate limiting (using in-memory cache for now)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "payment_cache",
        "TIMEOUT": 300,
        "OPTIONS": {
            "MAX_ENTRIES": 1000,
        },
    }
}

# ===============================
# DJANGO CHANNELS CONFIGURATION
# ===============================

# Channel layer configuration (using Redis)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL", "redis://localhost:6379/2")],
            "capacity": 1500,
            "expiry": 60,
        },
    },
}

# ===============================
# CELERY CONFIGURATION
# ===============================

# Celery Configuration Options
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://localhost:6379/1")

# Celery Task Configuration
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"
CELERY_ENABLE_UTC = True

# Celery Task Routing
CELERY_TASK_ROUTES = {
    "payment_system.tasks.*": {"queue": "payment_tasks"},
    "marketplace.tasks.*": {"queue": "marketplace_tasks"},
}

# Celery Worker Configuration
CELERY_WORKER_POOL_RESTARTS = True
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000
CELERY_WORKER_DISABLE_RATE_LIMITS = False

# Task execution settings
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes

# Result backend configuration
CELERY_RESULT_EXPIRES = 60 * 60 * 24  # Results expire after 24 hours

# Celery Beat scheduler (for periodic tasks)
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Celery Security
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_LOG_COLOR = False

# ===============================
# FEATURE FLAGS - SOLID REFACTORING
# ===============================

# Infrastructure Abstractions (Epic 1) & Service Layer (Epic 2)
# Controls whether to use new implementations or legacy code
# DEFAULT: TRUE - Use new service layer and infrastructure (Epic 1 & 2 complete)
# Set environment variable to "false" to rollback to legacy implementation
FEATURE_FLAGS = {
    # Infrastructure layer (Epic 1 - Story 1.6)
    # ✅ COMPLETE - Defaults to TRUE (use new infrastructure abstractions)
    "USE_NEW_STORAGE": os.getenv("FEATURE_FLAG_USE_NEW_STORAGE", "True").lower() == "true",
    "USE_NEW_EMAIL": os.getenv("FEATURE_FLAG_USE_NEW_EMAIL", "True").lower() == "true",
    "USE_NEW_PAYMENTS": os.getenv("FEATURE_FLAG_USE_NEW_PAYMENTS", "True").lower() == "true",
    # Service layer - Marketplace (Epic 2)
    # ✅ COMPLETE - Defaults to TRUE (use new service layer)
    "USE_SERVICE_LAYER_MARKETPLACE": os.getenv("FEATURE_FLAG_USE_SERVICE_LAYER_MARKETPLACE", "True").lower() == "true",
    "USE_SERVICE_LAYER_PRODUCTS": os.getenv("FEATURE_FLAG_USE_SERVICE_LAYER_PRODUCTS", "True").lower() == "true",
    "USE_SERVICE_LAYER_CART": os.getenv("FEATURE_FLAG_USE_SERVICE_LAYER_CART", "True").lower() == "true",
    "USE_SERVICE_LAYER_ORDERS": os.getenv("FEATURE_FLAG_USE_SERVICE_LAYER_ORDERS", "True").lower() == "true",
    # Service layer - Payments (Epic 4)
    # ⏳ PENDING - Defaults to FALSE (use legacy until Epic 4 complete)
    "USE_SERVICE_LAYER_PAYMENTS": os.getenv("FEATURE_FLAG_USE_SERVICE_LAYER_PAYMENTS", "False").lower() == "true",
}

# Infrastructure Configuration
# Used by DI container to determine which infrastructure implementations to use
INFRASTRUCTURE = {
    # Storage backend: 's3', 'local', 'minio'
    "STORAGE_BACKEND": os.getenv("STORAGE_BACKEND", "s3"),
    "STORAGE_CONFIG": {
        "s3": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "region": AWS_S3_REGION_NAME,
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
        },
        "local": {
            "base_path": BASE_DIR / "media_local",
        },
    },
    # Email backend: 'smtp', 'mock'
    "EMAIL_BACKEND_TYPE": os.getenv("EMAIL_BACKEND_TYPE", "smtp" if not DEBUG else "mock"),
    "EMAIL_CONFIG": {
        "smtp": {
            "host": EMAIL_HOST,
            "port": EMAIL_PORT,
            "use_tls": EMAIL_USE_TLS,
            "username": EMAIL_HOST_USER,
            "password": EMAIL_HOST_PASSWORD,
            "from_email": DEFAULT_FROM_EMAIL,
        },
        "mock": {
            "log_file": BASE_DIR / "logs" / "emails.log",
        },
    },
    # Payment provider: 'stripe', 'mock'
    "PAYMENT_PROVIDER": os.getenv("PAYMENT_PROVIDER", "stripe" if not DEBUG else "mock"),
    "PAYMENT_CONFIG": {
        "stripe": {
            "secret_key": STRIPE_SECRET_KEY,
            "publishable_key": STRIPE_PUBLISHABLE_KEY,
            "webhook_secret": STRIPE_WEBHOOK_SECRET,
            "webhook_connect_secret": STRIPE_WEBHOOK_CONNECT_SECRET,
            "application_fee_percent": STRIPE_APPLICATION_FEE_PERCENT,
        },
        "mock": {
            "enable_failures": os.getenv("MOCK_PAYMENT_ENABLE_FAILURES", "False").lower() == "true",
        },
    },
}

logger = logging.getLogger(__name__)
logger.info("=== FEATURE FLAGS STATUS ===")
for flag_name, flag_value in FEATURE_FLAGS.items():
    status = "ENABLED" if flag_value else "DISABLED"
    logger.info(f"{flag_name}: {status}")
logger.info(f"STORAGE_BACKEND: {INFRASTRUCTURE['STORAGE_BACKEND']}")
logger.info(f"EMAIL_BACKEND_TYPE: {INFRASTRUCTURE['EMAIL_BACKEND_TYPE']}")
logger.info(f"PAYMENT_PROVIDER: {INFRASTRUCTURE['PAYMENT_PROVIDER']}")
logger.info("=" * 30)
