# Generated by Django 5.2.4 on 2025-08-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_customuser_stripe_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("pt", "Portuguese"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("it", "Italian"),
                    ("ru", "Russian"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("zh", "Chinese"),
                    ("ar", "Arabic"),
                    ("hi", "Hindi"),
                    ("nl", "Dutch"),
                    ("sv", "Swedish"),
                    ("da", "Danish"),
                    ("no", "Norwegian"),
                    ("fi", "Finnish"),
                    ("pl", "Polish"),
                    ("tr", "Turkish"),
                    ("th", "Thai"),
                    ("vi", "Vietnamese"),
                    ("id", "Indonesian"),
                    ("ms", "Malay"),
                    ("he", "Hebrew"),
                    ("cs", "Czech"),
                    ("hu", "Hungarian"),
                    ("ro", "Romanian"),
                    ("bg", "Bulgarian"),
                    ("hr", "Croatian"),
                    ("sk", "Slovak"),
                    ("sl", "Slovenian"),
                    ("et", "Estonian"),
                    ("lv", "Latvian"),
                    ("lt", "Lithuanian"),
                    ("mt", "Maltese"),
                    ("ga", "Irish"),
                    ("cy", "Welsh"),
                    ("eu", "Basque"),
                    ("ca", "Catalan"),
                    ("gl", "Galician"),
                ],
                default="en",
                max_length=5,
            ),
        ),
    ]
