# Generated by Django 4.2.23 on 2025-08-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_customuser_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_picture_url",
            field=models.CharField(
                blank=True, help_text="S3 object key for profile picture", max_length=500, null=True
            ),
        ),
    ]
