# Generated by Django 5.2.4 on 2025-09-28 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_profile_profile_picture_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("seller", "Seller"), ("admin", "Admin")],
                default="user",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="SellerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                (
                    "seller_type",
                    models.CharField(
                        choices=[
                            ("manufacturer", "Manufacturer"),
                            ("designer", "Furniture Designer"),
                            ("restorer", "Furniture Restorer/Fixer"),
                            ("retailer", "Retailer/Curator"),
                            ("artisan", "Artisan/Craftsman"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "motivation",
                    models.TextField(help_text="Why they want to sell on Designia"),
                ),
                (
                    "portfolio_url",
                    models.URLField(help_text="Portfolio or website link"),
                ),
                (
                    "social_media_url",
                    models.URLField(blank=True, help_text="Social media link (optional)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("revision_requested", "Revision Requested"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Admin notes for review"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason for rejection"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved this application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rejected_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who rejected this application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rejected_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_application",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller Application",
                "verbose_name_plural": "Seller Applications",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerApplicationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="seller_applications/")),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop Photo"),
                            ("inventory", "Inventory Photo"),
                            ("product_sample", "Product Sample"),
                            ("business_setup", "Business Setup"),
                            ("tools_equipment", "Tools & Equipment"),
                            ("other", "Other"),
                        ],
                        default="workshop",
                        help_text="Type of business image",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description of what this image shows",
                        max_length=200,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="authentication.sellerapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "uploaded_at"],
            },
        ),
    ]
