# Generated by Django 5.2.5 on 2025-09-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_customuser_role_sellerapplication_and_more'),
    ]

    operations = [
    ]
