# Generated by Django 5.2.4 on 2025-12-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_alter_customuser_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("customer", "Customer"), ("seller", "Seller"), ("admin", "Admin")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
